### ISSUE TITLE
[FEATURE] Trusted IdP configuration options for shadow users and user logon

### ISSUE THREAD

**Issue by martinfrick** [SAP/terraform-provider-btp#372]
### What area do you want to see improved?

terraform provider

### Is your feature request related to a problem? Please describe.

As a customer I want to have an option, to configure the settings of my trusted IdPs, such as disabling the automated creation of shadow users, or the availability of the IdP for user logon. These settings can be configured using the SAP BTP CLI as follows.

btp update security/trust sap.custom --subaccount **--auto-create-shadow-users false**
btp update security/trust sap.default --subaccount **--available-for-user-logon false**

As of today, these configuration cannot be changed using the SAP BTP Terraform provider. 

### Describe the solution you would like

It would be amazing to have a new resource, allowing the more granular "configuration" or "update" of a Trusted Identity Provider, or giving users the option to provide additional parameters when configuring the trust setup resources, for instance: 

```hcl
resource "btp_subaccount_trust_configuration" "ias_trust" {
  subaccount_id     = "9ef6b690-a1b2-c3d4-e5f6-cf96ceba3904"
  identity_provider = "sap-demo.accounts.ondemand.com"
  auto_create_shadow_users = "false/true(Default)"
  available_for_user_logon = "false/true(Default)"
}
```

### Describe alternatives you have considered

Currently, the alternative of using the SAP BTP CLI solves the problem as kind of **workaround**.

### Additional context

https://help.sap.com/docs/btp/btp-cli-command-reference/btp-update-security-trust
(--available-for-user-logon [BOOL], --auto-create-shadow-users [BOOL])

https://help.sap.com/docs/authorization-and-trust-management-service/authorization-and-trust-management/switch-off-automatic-creation-of-shadow-users

https://help.sap.com/docs/btp/sap-business-technology-platform/hide-logon-link-for-default-identity-provider

**Comment by v0lkc** [comment]
@martinfrick thank you for placing this as a feature request. We'll be looking into both cases and keep you updated here.

**Comment by lechnerc77** [comment]
Tasks:

- [ ] Check diff between CREATE and UPDATE command of BTP CLI
- [ ] Add diff of available configuration options to schema of `btp_subaccount_trust_configuration` and `btp_globalaccount_trust_configuration`
- [ ] Add flow to implementation of resource namely execute two commands in corresponding functions to trigger the create and update calls in sequence. Handling of state must be considered so that in case the second call fails, a consistent state is stored.  This is needed for the CREATE and UPDATE functionality. 
- [ ] Enhance test cases and fixtures to consider additional settings. 
- [ ] Update documentation
