### ISSUE TITLE
[BUG] BadRequest when utilizing data source "btp_subaccount_service_plan"

### ISSUE THREAD

**Issue by SeanKilleen** [SAP/terraform-provider-btp#418]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of Terraform are you using?

1.5.6

### What type of issue are you facing

bug report

### Describe the bug

After defining a subaccount and an entitlement, when attempting to define an instance of an entitlement, [the documentation says](https://registry.terraform.io/providers/SAP/btp/latest/docs/resources/subaccount_service_instance):

> # The service plan ID can be looked up via the data source btp_subaccount_service_plan

But when defining a data element of that kind, for example: 

```tf
data "btp_subaccount_service_plan" "application_logs" {
  subaccount_id = btp_subaccount.products.id
  name          = var.logging_product_tier # "lite"
  offering_name = "application-logs"
}
```

And then defining the resource for the instance:

```tf
resource "btp_subaccount_service_instance" "logging_product1NameRedacted" {
  subaccount_id  = btp_subaccount.products.id
  serviceplan_id = data.btp_subaccount_service_plan.application_logs.serviceoffering_id
  name           = "product1NameRedacted-app-logs"
}
```

### Expected Behavior

Given the reproduction steps below and what I've read in the docs, I would expect the data source to be populated and the instance to be suggested for creation.

Instead, I see:

> Error: API Error Reading Resource Service Plan (Subaccount)
> │
> │   with module.product_environment.data.btp_subaccount_service_plan.application_logs,
> │   on modules\product_environment\main.tf line 8, in data "btp_subaccount_service_plan" "application_logs":
> │    8: data "btp_subaccount_service_plan" "application_logs" {
> │
> │ BadRequest

I also tried the data source using hard-coded values for the subaccount ID and `"lite"` for the service plan ID.

Since it's a BadRequest rather than a more specific error, I'm inclined to think this may be a bug.

### Steps To Reproduce

ℹ️ NOTE: I also tried the data source using hard-coded values for the subaccount ID and name in the data entry, to ensure my variables weren't messing it up.

```tf
resource "btp_subaccount" "products" {
  name      = var.product_subaccount_name # known to be correct
  subdomain = var.product_subaccount_subdomain # known to be correct
  region    = var.product_environment_region # known to be correct "us10"
}

data "btp_subaccount_service_plan" "application_logs" {
  subaccount_id = btp_subaccount.products.id
  name          = var.logging_product_tier # "lite"
  offering_name = "application-logs"
  depends_on    = [btp_subaccount.products]
}


resource "btp_subaccount_entitlement" "app_logging_service" {
  subaccount_id = btp_subaccount.products.id
  service_name  = "application-logs"
  plan_name     = var.logging_product_tier
}

resource "btp_subaccount_service_instance" "logging_product1NameRedacted" {
  subaccount_id  = btp_subaccount.products.id
  serviceplan_id = data.btp_subaccount_service_plan.application_logs.serviceoffering_id
  name           = "product1NameRedacted-app-logs"
}
```

### Additional context

I'm new to this and going off the docs but fully aware of the fact that this might be a silly mistake on my end.

**Comment by lechnerc77** [comment]
Analysis:
- The service is a non-cross-consumable service available on CF only
- The `list`  data source displays the service only if CF environment is enabled 
- The `get` data source throws an error (Bad Request) even if CF is enabled.

Works fine with cross-consumable services. 

Clarification with BTP CLI needed

**Comment by lechnerc77** [comment]
@SeanKilleen unfortunately this is not a bug but an impact of the environment-dependent availability of services in the SAP BTP.  You can create service instances in SAP BTP targeting different runtime environments namely Cloud Foundry, Kubernetes/Kyma and SAP BTP/other. Some services on support only specific runtime environments and can only be created there. You can see this in the SAP BTP Cockpit when creating a service instance via the UI (some services might even be visible only if the Cloud Foundry environment is enabled in your subaccount):

![Screenshot 2023-09-08 154516](https://github.com/SAP/terraform-provider-btp/assets/22294087/56b2b290-dd45-44a8-9cc2-346d23f395a9)

This availability is reflected in the tooling you can use to fetch information about the services as well as create services instances. In your case the service is available on Cloud Foundry only, so you are not able to fetch the service plan or create a service instance via the Terraform Provider for SAP BTP as this provider is only capable of handling services that are available in the runtime environment SAP BTP. Hence, the request you are executing, fails. 

The data source and the underlying API is a bit inconsistent here as it allows to specify the environment (see <https://registry.terraform.io/providers/SAP/btp/latest/docs/data-sources/subaccount_service_plans>), but this is not supported by the data source you are using. 

So this is not a bug, but a specific of the platform.

**Comment by SeanKilleen** [comment]
Hi @lechnerc77 thanks for the details. I'd just like to recap to confirm my understanding.

You're saying that I will not be able to use Terraform to create instances of entitlements in our BTP environment because that service is specific to the CloudFoundry runtime environment. And even though BTP itself encompasses all these environments, this Terraform provider product -- from a product direction standpoint -- is choosing to limit itself only to services that are within the "SAP BTP" runtime environment. This is fine if that's the case; I just want to make sure I'm clear.

It sounds like my only option would be to see if the CloudFoundry terraform provider -- the "wild west" we were seeking to avoid 😆 -- offers such functionality. 

Setting up and managing entitlements and their instances is a core part of why we'd want Terraform in the first place, because that represents a chunk of time in setting up and managing environment. So I may need to abandon this product for now. But I appreciate your support!

**Comment by lechnerc77** [comment]
Hi @SeanKilleen  

the BTP terraform provider restricts itself to the entities (which comprises the services) available for the SAP BTP. From the point of view of service instances you can manage `cross-consumable` services with it. This restriction (beside some technical aspects) is also due to the fact that there are existing providers for Kubernetes as well as for Cloud Foundry that we do not want to duplicate. 

Concerning your setup: I do not think that this severely impacts the setup of your accounts:

- The basic setup of your accounts including the assignment of entitlements to your subaccounts, creating role collections etc. is covered by the terraform provider. This also comprises the creation of instances of these environments. 
- As soon as things become "runtime environment" specific, things need to be managed by the runtime-specific providers namely the Cloud Foundry or Kubernetes ones. For Cloud Foundry this means e.g. the creation of spaces or of service instances and bindings within the runtime environment. 

Comparing that to the options you have to automate the setup via CLIs, you will face the same limits: the BTP CLI is capable of the BTP-specifics but e.g. cannot create CF spaces or Kubernetes namespaces. For the later two you need to use the CloudFoundry CLI or kubectl in order to handle the corresponding resources.

I agree that the experience might not be as smooth as one would wish, but you should be able to do your setup Terraform based however need to combine several providers. However, if you face any limitation from that approach, I am happy to jump on a call to learn about those.

**Comment by SeanKilleen** [comment]
@lechnerc77 totally fair and I appreciate the confirmation / clarification. I think at first distinction was lost on me but I've got it now. 👍 Thanks again!
