### ISSUE TITLE
[BUG] Terraform New Version Error (1.6.1)

### ISSUE THREAD

**Issue by mahesh0431** [SAP/terraform-provider-btp#476]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of Terraform are you using?

1.6.1

### What type of issue are you facing

bug report

### Describe the bug

Terraform apply command gives the below error when I upgraded to 1.6.1 from 1.5.7.

│ Error: Resource Type Not Found
│ 
│   with btp_subaccount.project,
│   on main.tf line 15, in resource "btp_subaccount" "project":
│   15: resource "btp_subaccount" "project" {
│ 
│ No resource type named "btp_subaccount" was found in the provider.

**Comment by lechnerc77** [comment]
@mahesh0431 Thanks for bringing this to our attention. This is an issue within the Terraform dependencies that was fixed by the upgrade of the Terraform plugin framework with PR #463 . This fix will land in the next release of our provider that we plan to release in November (see [Milestones](https://github.com/SAP/terraform-provider-btp/milestones))

Until then please downgrade to version 1.5.7 of the Terraform CLI.

**Comment by lechnerc77** [comment]
Fixed with #463
