### ISSUE TITLE
Directory Update error : API Error Updating Resource Directory

### ISSUE THREAD

**Issue by tb000000** [SAP/terraform-provider-btp#648]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of the Terraform provider are you using?

1.0.0.rc1

### What version of the Terraform CLI are you using?

v1.5.4

### What type of issue are you facing

bug report

### Describe the bug

We want update a directory to enable the entitlement and user management.
We add this code <features    = ["DEFAULT","ENTITLEMENTS","AUTHORIZATIONS"]> to the terraform script.

We got this error after <terraform apply> command.

 _**Error: API Error Updating Resource Directory
│
│   with module.dir_db_company_a.btp_directory.directory,
│   on module_directory/main.tf line 4, in resource "btp_directory" "directory":
│    4: resource "btp_directory" "directory" {
│
│ Update of Directory Features is not supported**_

**Comment by lechnerc77** [comment]
@tb000000 this is a known missing feature and tracked in issue #471. Please track the progress of the feature implementation via the existing issue. 

Currently the workaround depending on your setup would be :

- remove the existing directory and create a new one with features using Terraform.

or 

- remove the directory from the Terraform state, enable the features via the BTP CLI and import the directory into your Terraform state so that consequent management of the directory can be done via Terraform.

I close this issue as duplicate.
