### ISSUE TITLE
[FEATURE] Resource to create 'role' in subaccount

### ISSUE THREAD

**Issue by juliankuipers-alliander** [SAP/terraform-provider-btp#841]
### What area do you want to see improved?

terraform provider

### Is your feature request related to a problem? Please describe.

I can create and assign a role collection with this provider, but I can't create a role with this provider. I miss this functionality. For example: the alm-ts app (cTMS) has a role template for ImportOperator from which you can create a role and assign specific values to the attribute TmsNodesImport.

### Describe the solution you would like

It would be great to have a resource with which I can create roles in my subaccount. With this I can create roles from a template. I can provide the role name, description, template and assign the attributes.

### Describe alternatives you have considered

Alternative would be creating the role manually on BTP and using the provider to assign it to a role collection and users.

**Comment by lechnerc77** [comment]
Tasks to enable roles:

- [ ] Activate role-specific resources in `provider.go` for the three levels global account, directory and subaccount
- [ ] Validate implementation of role-specific resources wrt to potential changes on platform as well as to changes in provider framework since initial implementation
- [ ] Add missing test cases for resources

*Remark*: Data sources for roles are already available

**Comment by lechnerc77** [comment]
@juliankuipers-alliander fyi:  resources will be implemented.
