### ISSUE TITLE
[FEATURE] Trust Configuration setting to uncheck : Available for User Logon of Default Identity provider

### ISSUE THREAD

**Issue by Singbad** [SAP/terraform-provider-btp#962]
### What area do you want to see improved?

terraform provider

### Is your feature request related to a problem? Please describe.

No

### Describe the solution you would like

I would like to have an option in trust configurations to uncheck the default login method with resource option but it seems it's not available

**Comment by lechnerc77** [comment]
@Singbad Thanks for your request.  Can you provide a bit more context on the scenario?
Do you want to target the default setting in the SAP Cloud Identity Services as described [here](https://help.sap.com/docs/cloud-identity-services/cloud-identity-services/choose-default-identity-provider-for-application)?

**Comment by Singbad** [comment]
Hello @lechnerc77 Good day,

whenever the subaccount is created with terraform resource it seems trust configuration is also created for "Default Identity provider" and its always checked rather we should have option to check or uncheck with boolean values true or false.

let me know if I have clarified your doubt?

**Comment by Singbad** [comment]
![user-logon](https://github.com/user-attachments/assets/1571d076-26c1-4365-aefa-f58da9bd0f1a)

**Comment by lechnerc77** [comment]
@Singbad This feature is available on the resource [`btp_subaccount_trust_configuration`](https://registry.terraform.io/providers/SAP/btp/1.8.0/docs/resources/subaccount_trust_configuration#available_for_user_logon-4) as `available_for_user_logon`

As you pointed out correctly the SAP Default IdP trust including this setting is created upon subaccount creation. Hence, the process of getting things sorted out must be a two step process if you want to switch off the default IdP and exclusively use the custom IdP:

Step 1: Do the setup of your subaccount including the trust configuration for your custom IdP

Once this is completed, **make sure that the custom IdP is available for logon and you can successfully logon to SAP BTP**. If this is the case, execute:

Step 2:  import the SAP Default IdP and set the configuraton as you want to.

You find a sample code snippet here: https://github.com/SAP-samples/btp-terraform-samples/blob/main/released/discovery_center/mission_4024/step2/main.tf

However make sure that do not close up the account due to missing configurations and nobody can logon any more.

**Comment by Singbad** [comment]
Hello @lechnerc77, I would like to thank you your solution works :)

I was able to implement step no 2 successfully and hence it satisfied my requirements.
