### ISSUE TITLE
[BUG] Need info on storage of statefile and Github integrations 

### ISSUE THREAD

**Issue by Singbad** [SAP/terraform-provider-btp#966]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of the Terraform provider are you using?

1.8.0

### What version of the Terraform CLI are you using?

1.8.0

### What type of issue are you facing

documentation issue

### Describe the bug

Our team is currently in the process of automating our infrastructure on BTP and Cloud Foundry. We have made significant progress but need some clarification to ensure we are following best practices. Currently, we are running Terraform commands locally, which we have identified as potentially risky.

We have a few outstanding queries from our team:

1. Where can we securely store the state file for our project? Options we are considering include AWS S3, BTP Object Store, or other suitable solutions.
2. How can we integrate GitHub Actions with our project?
3. We also need information regarding the "Runner." Specifically, where it should be executed—whether on a server or in a Docker container.

Any expert advice on these matters would be greatly appreciated.

Thank you for your assistance.

### Expected Behavior

Our team is currently in the process of automating our infrastructure on BTP and Cloud Foundry. We have made significant progress but need some clarification to ensure we are following best practices. Currently, we are running Terraform commands locally, which we have identified as potentially risky.

We have a few outstanding queries from our team:

1. Where can we securely store the state file for our project? Options we are considering include AWS S3, BTP Object Store, or other suitable solutions.
2. How can we integrate GitHub Actions with our project?
3. We also need information regarding the "Runner." Specifically, where it should be executed—whether on a server or in a Docker container.

Any expert advice on these matters would be greatly appreciated.

Thank you for your assistance.

### Additional context

na

**Comment by lechnerc77** [comment]
@Singbad Issues are ment for reporting Bugs or feature requests. If you have questions, please use the [GitHub Discussions](https://github.com/SAP/terraform-provider-btp/discussions) to ask questions, especially these generic ones. 

I created a question there for you: <https://github.com/SAP/terraform-provider-btp/discussions/967>
Answers will be added to the discussion, this issue will be closed

**Comment by vipinvkmenon** [comment]
> Where can we securely store the state file for our project? Options we are considering include AWS S3, BTP Object Store, or other suitable solutions.

From the `terraform provider` perspective there isn't a difference or dependency between using any of the backends. All backends supported by Terraform officially should work. It would be better to look at the [official documentation](https://developer.hashicorp.com/terraform/language/backend) from Terraform and documentation for specific backends for the best practices. For E.G [S3](https://docs.aws.amazon.com/prescriptive-guidance/latest/terraform-aws-provider-best-practices/backend.html).

We do have documented some [examples](https://github.com/SAP-samples/btp-terraform-samples/tree/main/released/terraform-be) as a reference to how backends (in general) in terraform can be used.

> How can we integrate GitHub Actions with our project?

A good source for the documentation for this would be from the [Terraform official documentation](https://developer.hashicorp.com/terraform/tutorials/automation/github-actions) as this is also generic to Terraform and not the providers themselves. 
While we don't have any explicit sample for this, you could refer to the way we have setup our terraform [test pipeline](https://github.com/SAP-samples/btp-terraform-samples/blob/main/.github/workflows/scenario-test.yml).

> We also need information regarding the "Runner." Specifically, where it should be executed—whether on a server or in a Docker container.

What do you mean by server or docker? In all cases, the github actions would run within containers. Could you elaborate on the question?  Do you mean `self-hosted` servers vs `github-hosted` servers?

Since these are questions and not a specific bug, it would be better to close this and have the discussion as a Q&A.
